---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iotapp-pvc
  labels:
    app: iotapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iotapp-cm
  labels:
    app: iotapp
data:
  BROKER_HOST: "192.168.15.6"
  BROKER_PORT: "30883"
  DB_NAME: iot
  DB_USER: postgres
  DB_PASSWORD: dbiot
  DB_HOST: "192.168.15.2"
  DB_PORT: "102"
  DEVICE: d1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotapp
  labels:
    app: iotapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotapp
  template:
    metadata:
      labels:
        app: iotapp
    spec:
      containers:
      - name: iotapp
        image: sayonarasantos/iot-app:2.0
        envFrom:
        - configMapRef:
            name: iotapp-cm
        volumeMounts:
        - name: iotapp-volume
          mountPath: /app/logs
        command: ["/bin/bash"]
        args: ["-c", "python server.py ${DEVICE}"]
      volumes:
        - name: iotapp-volume
          persistentVolumeClaim:
            claimName: iotapp-pvc
